---
# This playbook deploys the whole application stack in this site.

- hosts: localhost
  remote_user: root

  vars_prompt:
    - name: "platform"
      prompt: "Running oc or k8s?"
      default: "k8s"
      private: no

  tasks:
    - fail: msg="Unrecognised platform. Please choose between 'k8s' or 'oc'"
      when: platform not in ["k8s", "oc"]

  roles:
    - strimzi
    - kubeless
