---
# This playbook contains plays to deploy a strimzi (kafka) cluster
# in an isolated namespace

- block:
    - name: Login as system admin
      command: oc login -u system:admin

    - name: Create a '{{ kafka_namespace }}' namespace
      command: oc new-project {{ kafka_namespace }}

    - name: Write correct namespace to Strimzi templates
      replace:
        path: "{{ item }}"
        regexp: "namespace: .*"
        replace: "namespace: {{ kafka_namespace }}"
      with_fileglob:
        - "cluster-operator/*RoleBinding*.yaml"

    - name: Install Strimzi Custom Resource Definitions
      command: oc create -f {{ item }} -n {{ kafka_namespace }}
      with_fileglob:
        - "cluster-operator/*.yaml"
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr

    - name: Process the app template
      command: oc create -f {{ item }}
      with_fileglob:
        - "*template*.yaml"
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr

    - name: Create the app
      command: oc new-app strimzi-ephemeral --param=CLUSTER_NAME={{ kafka_cluster_name }}

  # Rescue allows recovery from failed tasks, so cleaning
  # up can be done here
  rescue:
    - debug:
        msg: "Strimzi playbook failed. Cleaning up..."

    - name: Deleting {{ kafka_namespace }} namespace
      command: oc delete project {{ kafka_namespace }}
