- block:
    - name: Login as system admin
      command: oc login -u system:admin

    - name: Create a '{{ kafka_namespace }}' namespace
      command: oc new-project {{ kafka_namespace }}

    - name: Download strimzi installation files
      shell: "curl -s -L {{ install_url }} \\ 
      | sed 's/namespace: .*/namespace: {{ kafka_namespace }}/' \\
      | oc -n {{ kafka_namespace }} apply -f -"
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr

    - name: Create the cluster
      shell: oc create -f {{ item }} -n {{ kafka_namespace }}
      with_fileglob:
      - "persistent-template.yaml"
      ignore_errors: True

  # Clean up if the tasks fail
  rescue:
    - debug:
        msg: "Strimzi playbook failed. Cleaning up..."

    - name: Deleting {{ kafka_namespace }} namespace
      command: oc delete project {{ kafka_namespace }}