---
# This playbook contains plays to deploy a kubeless cluster
# in an isolated namespace

- set_fact:
    k8s_install_url: "https://github.com/kubeless/kubeless/releases/download/v1.0.2/kubeless-v1.0.2.yaml"
    oc_install_url: "https://github.com/kubeless/kubeless/releases/download/v1.0.2/kubeless-openshift-v1.0.2.yaml"

- block:
    - include_tasks: openshift.yml
  when: platform == "oc"

- block:
    - include_tasks: kubernetes.yml
  when: platform == "k8s"
