---
# This playbook contains plays to deploy a kubeless cluster
# in an isolated namespace

- block:
    - include_tasks: openshift.yml
  when: platform == "openshift"

- block:
    - include_tasks: kubernetes.yml
  when: platform == "kubernetes"
