---
# This playbook contains plays to deploy a kubeless cluster
# in an isolated namespace

- name: Login as system admin
  command: oc login -u system:admin

- name: Create a '{{ namespace }}' namespace
  command: oc create ns {{ namespace }}

- name: Create the kubeless deployment
  command: oc create -f https://github.com/kubeless/kubeless/releases/download/v1.0.0-alpha.7/kubeless-openshift-v1.0.0-alpha.7.yaml -n {{ namespace }}

# Create trigger controller deployment
- set_fact: 
    kafka_brokers: "kafka:9092"

- template:
    src: trigger-controller.yml.j2
    dest: /tmp/trigger-controller.yaml
  
- name: Create trigger controller deployment
  command: oc create -f /tmp/trigger-controller.yaml -n {{ namespace }}

- file: path=/tmp/trigger-controller.yaml state=absent