---
# This playbook contains plays to deploy a kubeless cluster
# in an isolated namespace

- block:
    - include_tasks: openshift.yml
  when: platform == "oc"

- block:
    - include_tasks: kubernetes.yml
  when: platform == "k8s"
