- set_fact:
    install_url: "https://github.com/kubeless/kubeless/releases/download/v1.0.1/kubeless-openshift-v1.0.1.yaml"

- block:
    - name: Create a '{{ kubeless_namespace }}' namespace
      command: "oc new-project {{ kubeless_namespace }}"

    - name: Create the kubeless deployment
      command: oc create -f {{ install_url }} -n {{ kubeless_namespace }}
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr
      when: platform == "openshift"

    # Create trigger controller deployment
    # This configuration is needed for custom Kafka instances
    - template:
        src: trigger-controller.yml.j2
        dest: /tmp/trigger-controller.yaml

    - name: Create trigger controller deployment
      command: "oc create -f /tmp/trigger-controller.yaml -n {{ kubeless_namespace }}"
      register: result
      failed_when: result.stderr != "" and "already exists" not in result.stderr

    - file: path=/tmp/trigger-controller.yaml state=absent

  # Clean up if the tasks fail
  rescue:
    - debug:
        msg: "Kubeless playbook failed. Cleaning up..."

    - name: Deleting {{ kubeless_namespace }} namespace
      command: "oc delete project {{ kubeless_namespace }}"
